### ISSUE TITLE
Test with semantic kernel framework

### ISSUE THREAD

**Issue by iddelacruz** [MickMelon/PedGPT#4]
Hi dude.
First, good job with this project. I was looking for something write in C# to start testing and found your project. I cloned the repo and I started to integrate semantic kernel : https://learn.microsoft.com/en-us/semantic-kernel/whatissk cause I think can be integrate as part of your main logic without risks. SK skills for example, can be integrated inside commands to decouple from any external logic.

Thanks again

**Comment by MickMelon** [comment]
Hey, thanks!

I'm very new to this world, so semantic kernel is not something I'd heard of before. It sounds very interesting, I'll definitely give this a read!

I'd love to hear how you get on :) 

Are you looking to build something specifically with GTA/FiveM, or more of a general .NET agent? I'm asking because I feel like we could make this application more generalised, rather than being GTA-specific. My original idea was to create autonomous peds in GTA and perhaps make it suitable for other games as well. I think there are many potential applications for a .NET agent even outside games.
